### ISSUE TITLE
Tune chunk size

### ISSUE THREAD

**Issue by tomwilkie** [tomwilkie/frankenstein#10]
Currently 10mins, should be 1hr.

**Comment by jml** [comment]
Why should it be 1hr?

**Comment by tomwilkie** [comment]
We should investigate what the right number is, but the parameters are:
- data batched up in the ingesters is a risk of loss in event of machine failure.  we should bound this.
- chunks are 1kb, and making bigger chunks doesn't necessarily make things more efficient.  we should try and fill chunks as much as possible (something we already monitoring for).

Ticket should really say "max 1hr" to bound the loss, if that give good utilization

**Comment by jml** [comment]
This issue was moved to https://github.com/weaveworks/frankenstein/issues/11
