### ISSUE TITLE
Use packages, clean up code etc

### ISSUE THREAD

**Issue by tomwilkie** [tomwilkie/frankenstein#15]

**Comment by jml** [comment]
@tomwilkie This will need a better description if someone else can attempt it.

**Comment by tomwilkie** [comment]
I guess we probably want a package for each component - ingestor, distributor, querier?

And by code cleaner I just mean removing TODOs, adding unit tests, improving code smells, better decoupling, be more stringent in code reviews.

**Comment by jml** [comment]
OK. I suggest we make the package-per-component bit the thing for this ticket and do the other stuff incrementally as we make other changes.

**Comment by tomwilkie** [comment]
Agreed!

**Comment by jml** [comment]
This issue was moved to https://github.com/weaveworks/frankenstein/issues/16
