### ISSUE TITLE
Move "Getting Started" doc into README

### ISSUE THREAD

**Issue by jml** [tomwilkie/frankenstein#23]
Document is here: https://docs.google.com/document/d/13NHmaqh7IKIVUw2NYqQkt8JVuHLZp5lpKxFmFwtPjcg/edit#heading=h.96i7uwaaxgku

Should be part of the README.

**Comment by jml** [comment]
@tomwilkie I filed this while we were talking in person, but I've forgotten—why do we want this in time for the meetup?

**Comment by tomwilkie** [comment]
Self service sign up is super important for adoption. These institutions
enable self service signup. We want adoption.

We should also loop in @davkal.

**Comment by jml** [comment]
Oh right. Actually reading the "Getting Started" doc I see it's about cloud adoption, not running yourself.
