### ISSUE TITLE
Frankenstein needs to accept gRPC

### ISSUE THREAD

**Issue by tomwilkie** [tomwilkie/frankenstein#5]

**Comment by jml** [comment]
@tomwilkie Why?

**Comment by tomwilkie** [comment]
Upstream has gone with gRPC for the generic write path, we want people to use vanilla prometheus for their retrievers:

https://github.com/prometheus/prometheus/pull/1930

**Comment by tomwilkie** [comment]
See https://github.com/prometheus/prometheus/pull/1957

**Comment by jml** [comment]
This issue was moved to https://github.com/weaveworks/frankenstein/issues/6
