### ISSUE TITLE
Parallelise distributor -> ingester RPC

### ISSUE THREAD

**Issue by tomwilkie** [tomwilkie/frankenstein#7]

**Comment by tomwilkie** [comment]
This limits scalability.

**Comment by jml** [comment]
Which RPCs need to be parallelised? This one? https://github.com/tomwilkie/frankenstein/blob/master/distributor.go#L228

**Comment by tomwilkie** [comment]
I was thinking this, but it looks like you beat me to it: https://github.com/tomwilkie/frankenstein/blob/master/distributor.go#L157

That one isn't particularly performance sensitive.  Will need to check query path is completely parallelised.

**Comment by jml** [comment]
This issue was moved to https://github.com/weaveworks/frankenstein/issues/8
