### ISSUE TITLE
Larger buckets in chunk index

### ISSUE THREAD

**Issue by tomwilkie** [tomwilkie/frankenstein#9]
Should reduce index size, super important for scalability.

**Comment by jml** [comment]
@tomwilkie Do you have some idea for how much larger they should be, or thoughts on how to determine how much larger?

**Comment by tomwilkie** [comment]
Chunk index 'big' bucket size mainly affects the number of range queries you need to do on query.  Smaller buckets = more range queries = more dynamodb cost & slower queries.

OTOH larger buckets mean more chunks / bucket, which means more items returned in the range queries.  Limit on dynamodb range queries is 25 items before you start paging.  So we should look and see how many chunks / query we are getting, and tune that until it hits 25.  I have a feeling it will be 24hrs...

**Comment by jml** [comment]
This issue was moved to https://github.com/weaveworks/frankenstein/issues/10
